[2023-07-21T14:43:42.749+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=RSS_feed_dag/run_id=manual__2023-07-21T14:43:34.902120+00:00/task_id=load_to_db permission to 509
[2023-07-21T14:43:42.782+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=RSS_feed_dag/run_id=manual__2023-07-21T14:43:34.902120+00:00/task_id=load_to_db permission to 509
[2023-07-21T14:43:42.816+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: RSS_feed_dag.load_to_db manual__2023-07-21T14:43:34.902120+00:00 [queued]>
[2023-07-21T14:43:42.828+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: RSS_feed_dag.load_to_db manual__2023-07-21T14:43:34.902120+00:00 [queued]>
[2023-07-21T14:43:42.828+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-21T14:43:42.848+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_to_db> on 2023-07-21 14:43:34.902120+00:00
[2023-07-21T14:43:42.853+0000] {standard_task_runner.py:57} INFO - Started process 77 to run task
[2023-07-21T14:43:42.856+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'RSS_feed_dag', 'load_to_db', 'manual__2023-07-21T14:43:34.902120+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/saiswaroopa_rss_dag.py', '--cfg-path', '/tmp/tmpjrhvnog8']
[2023-07-21T14:43:42.859+0000] {standard_task_runner.py:85} INFO - Job 71: Subtask load_to_db
[2023-07-21T14:43:42.910+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=RSS_feed_dag/run_id=manual__2023-07-21T14:43:34.902120+00:00/task_id=load_to_db permission to 509
[2023-07-21T14:43:42.912+0000] {task_command.py:410} INFO - Running <TaskInstance: RSS_feed_dag.load_to_db manual__2023-07-21T14:43:34.902120+00:00 [running]> on host c02534ee6e6b
[2023-07-21T14:43:43.194+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='RSS_feed_dag' AIRFLOW_CTX_TASK_ID='load_to_db' AIRFLOW_CTX_EXECUTION_DATE='2023-07-21T14:43:34.902120+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-21T14:43:34.902120+00:00'
[2023-07-21T14:43:43.215+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/saiswaroopa_rss_dag.py", line 66, in load_to_db
    conn = sqlite3.connect(db_location)
sqlite3.OperationalError: unable to open database file
[2023-07-21T14:43:43.259+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=RSS_feed_dag, task_id=load_to_db, execution_date=20230721T144334, start_date=20230721T144342, end_date=20230721T144343
[2023-07-21T14:43:43.279+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 71 for task load_to_db (unable to open database file; 77)
[2023-07-21T14:43:43.311+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-21T14:43:43.364+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
