[2023-07-21T18:15:26.123+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=RSS_feed_dag/run_id=manual__2023-07-21T18:15:17.166027+00:00/task_id=load_to_db permission to 509
[2023-07-21T18:15:26.160+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=RSS_feed_dag/run_id=manual__2023-07-21T18:15:17.166027+00:00/task_id=load_to_db permission to 509
[2023-07-21T18:15:26.198+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: RSS_feed_dag.load_to_db manual__2023-07-21T18:15:17.166027+00:00 [queued]>
[2023-07-21T18:15:26.209+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: RSS_feed_dag.load_to_db manual__2023-07-21T18:15:17.166027+00:00 [queued]>
[2023-07-21T18:15:26.210+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-21T18:15:26.227+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_to_db> on 2023-07-21 18:15:17.166027+00:00
[2023-07-21T18:15:26.232+0000] {standard_task_runner.py:57} INFO - Started process 87 to run task
[2023-07-21T18:15:26.235+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'RSS_feed_dag', 'load_to_db', 'manual__2023-07-21T18:15:17.166027+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/saiswaroopa_rss_dag.py', '--cfg-path', '/tmp/tmp8oo2j0hw']
[2023-07-21T18:15:26.239+0000] {standard_task_runner.py:85} INFO - Job 98: Subtask load_to_db
[2023-07-21T18:15:26.286+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=RSS_feed_dag/run_id=manual__2023-07-21T18:15:17.166027+00:00/task_id=load_to_db permission to 509
[2023-07-21T18:15:26.288+0000] {task_command.py:410} INFO - Running <TaskInstance: RSS_feed_dag.load_to_db manual__2023-07-21T18:15:17.166027+00:00 [running]> on host c02534ee6e6b
[2023-07-21T18:15:26.559+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='RSS_feed_dag' AIRFLOW_CTX_TASK_ID='load_to_db' AIRFLOW_CTX_EXECUTION_DATE='2023-07-21T18:15:17.166027+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-21T18:15:17.166027+00:00'
[2023-07-21T18:15:26.572+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/saiswaroopa_rss_dag.py", line 53, in load_to_db
    with open(curated_file_name, 'r', newline='') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2023-07-21T18:15:26.592+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=RSS_feed_dag, task_id=load_to_db, execution_date=20230721T181517, start_date=20230721T181526, end_date=20230721T181526
[2023-07-21T18:15:26.608+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 98 for task load_to_db (expected str, bytes or os.PathLike object, not NoneType; 87)
[2023-07-21T18:15:26.652+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-21T18:15:26.694+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
