[2023-07-21T14:36:26.117+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=RSS_feed_dag/run_id=manual__2023-07-21T14:36:18.440120+00:00/task_id=load_to_db permission to 509
[2023-07-21T14:36:26.150+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=RSS_feed_dag/run_id=manual__2023-07-21T14:36:18.440120+00:00/task_id=load_to_db permission to 509
[2023-07-21T14:36:26.182+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: RSS_feed_dag.load_to_db manual__2023-07-21T14:36:18.440120+00:00 [queued]>
[2023-07-21T14:36:26.194+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: RSS_feed_dag.load_to_db manual__2023-07-21T14:36:18.440120+00:00 [queued]>
[2023-07-21T14:36:26.194+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-21T14:36:26.212+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_to_db> on 2023-07-21 14:36:18.440120+00:00
[2023-07-21T14:36:26.218+0000] {standard_task_runner.py:57} INFO - Started process 105 to run task
[2023-07-21T14:36:26.221+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'RSS_feed_dag', 'load_to_db', 'manual__2023-07-21T14:36:18.440120+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/saiswaroopa_rss_dag.py', '--cfg-path', '/tmp/tmpme8om5ly']
[2023-07-21T14:36:26.224+0000] {standard_task_runner.py:85} INFO - Job 63: Subtask load_to_db
[2023-07-21T14:36:26.274+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=RSS_feed_dag/run_id=manual__2023-07-21T14:36:18.440120+00:00/task_id=load_to_db permission to 509
[2023-07-21T14:36:26.276+0000] {task_command.py:410} INFO - Running <TaskInstance: RSS_feed_dag.load_to_db manual__2023-07-21T14:36:18.440120+00:00 [running]> on host c02534ee6e6b
[2023-07-21T14:36:26.546+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='RSS_feed_dag' AIRFLOW_CTX_TASK_ID='load_to_db' AIRFLOW_CTX_EXECUTION_DATE='2023-07-21T14:36:18.440120+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-21T14:36:18.440120+00:00'
[2023-07-21T14:36:26.559+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/saiswaroopa_rss_dag.py", line 54, in load_to_db
    with open(curated_file_name, 'r', newline='') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2023-07-21T14:36:26.573+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=RSS_feed_dag, task_id=load_to_db, execution_date=20230721T143618, start_date=20230721T143626, end_date=20230721T143626
[2023-07-21T14:36:26.590+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 63 for task load_to_db (expected str, bytes or os.PathLike object, not NoneType; 105)
[2023-07-21T14:36:26.635+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-21T14:36:26.664+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
