[2023-07-21T10:16:42.388+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=RSS_feed_dag/run_id=manual__2023-07-21T10:09:06.018879+00:00/task_id=load_to_database permission to 509
[2023-07-21T10:16:42.500+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=RSS_feed_dag/run_id=manual__2023-07-21T10:09:06.018879+00:00/task_id=load_to_database permission to 509
[2023-07-21T10:16:42.557+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: RSS_feed_dag.load_to_database manual__2023-07-21T10:09:06.018879+00:00 [queued]>
[2023-07-21T10:16:42.575+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: RSS_feed_dag.load_to_database manual__2023-07-21T10:09:06.018879+00:00 [queued]>
[2023-07-21T10:16:42.576+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-21T10:16:42.614+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_to_database> on 2023-07-21 10:09:06.018879+00:00
[2023-07-21T10:16:42.621+0000] {standard_task_runner.py:57} INFO - Started process 68 to run task
[2023-07-21T10:16:42.627+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'RSS_feed_dag', 'load_to_database', 'manual__2023-07-21T10:09:06.018879+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/saiswaroopa_rss_dag.py', '--cfg-path', '/tmp/tmpsqlnobtc']
[2023-07-21T10:16:42.630+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask load_to_database
[2023-07-21T10:16:42.717+0000] {logging_mixin.py:150} INFO - Changing /opt/***/logs/dag_id=RSS_feed_dag/run_id=manual__2023-07-21T10:09:06.018879+00:00/task_id=load_to_database permission to 509
[2023-07-21T10:16:42.720+0000] {task_command.py:410} INFO - Running <TaskInstance: RSS_feed_dag.load_to_database manual__2023-07-21T10:09:06.018879+00:00 [running]> on host c02534ee6e6b
[2023-07-21T10:16:43.161+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='RSS_feed_dag' AIRFLOW_CTX_TASK_ID='load_to_database' AIRFLOW_CTX_EXECUTION_DATE='2023-07-21T10:09:06.018879+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-21T10:09:06.018879+00:00'
[2023-07-21T10:16:43.190+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/saiswaroopa_rss_dag.py", line 65, in load_to_database
    conn = pyodbc.connect(connection_string)
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)")
[2023-07-21T10:16:43.207+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=RSS_feed_dag, task_id=load_to_database, execution_date=20230721T100906, start_date=20230721T101642, end_date=20230721T101643
[2023-07-21T10:16:43.229+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 32 for task load_to_database (('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)"); 68)
[2023-07-21T10:16:43.282+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-21T10:16:43.336+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
